// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRNicoNico.Models;

namespace SRNicoNico.Migrations {
    [DbContext(typeof(ViewerDbContext))]
    partial class ViewerDbContextModelSnapshot : ModelSnapshot {
        protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12");

            modelBuilder.Entity("SRNicoNico.Entities.LocalHistory", b => {
                b.Property<string>("VideoId")
                    .HasColumnType("TEXT");

                b.Property<int>("Duration")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("LastWatchedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("PostedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("ShortDescription")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("ThumbnailUrl")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("WatchCount")
                    .HasColumnType("INTEGER");

                b.HasKey("VideoId");

                b.HasIndex("LastWatchedAt");

                b.ToTable("LocalHistory");
            });
#pragma warning restore 612, 618
        }
    }
}
